FROM python:3.8-buster

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install nvflare==2.4.0
RUN python3 -m pip install scipy
RUN python3 -m pip install -U matplotlib
RUN python3 -m pip install nilearn

WORKDIR /workspace/

ENV PYTHONPATH=$PYTHONPATH:/workspace/app/code/
ENV NVFLARE_POC_WORKSPACE=/workspace/poc-workspace

CMD ["/bin/bash"]